### ISSUE TITLE
4 spaces indenting

### ISSUE THREAD

**Issue by kujohn** [yosssi/gcss#11]
Is there an option to indent with 4 spaces instead of 2? Getting invalid indents while compiling:

```
indent is invalid [line: 2]
```

**Comment by yosssi** [comment]
@kujohn For now, there's no way to have GCSS accept 4 spaces as an indent. Are there any problems when we use 2 spaces as an indent?

**Comment by kujohn** [comment]
It's just that the codebases I work with uses 4 spaces indent and it is saved in my vim settings. I guess there may be a way to have 2 spaces indent on gcss files.

**Comment by yosssi** [comment]
@kujohn You can use [vim-gcss](https://github.com/yosssi/vim-gcss) for setting Vim to use 2 spaces indent when you edit a GCSS file. I know other CSS preprocessors like Stylus allow multi kind of spaces as an indent but I think unity is better than customizablity and so I provide 2 spaces indent only for now. I'll consider to allow other kind of spaces indent when some issues will occur.

**Comment by kujohn** [comment]
Thank you, [vim-gcss](https://github.com/yosssi/vim-gcss) works great on 2 space tabs.

**Comment by yosssi** [comment]
Thanks for your checking!
