### ISSUE TITLE
Allow optional curly brackets (a la .scss vs .sass)

### ISSUE THREAD

**Issue by ciarand** [yosssi/gcss#4]
Is this something you'd consider adding if I put together a PR for it?

**Comment by yosssi** [comment]
I'm not sure if we should allow optional curly braces for now. Allowing optional curly braces might make the GCSS syntax and compiler's implementation complex. If I would see a lot of demand for doing this, I would consider implementing this function.

**Comment by ciarand** [comment]
Ok, that's reasonable. I'm going to go ahead and close this for now then.

**Comment by yosssi** [comment]
Thanks for your understanding.

**Comment by kdar** [comment]
I think it's unfortunate that this can't parse standard CSS files. I'm under the personal opinion that code blocks by indentation is bad (and so do the Go authors).
